import os, pandas
from cassandra.cluster import Cluster

header = [
'DATA_GERACAO',
'HORA_GERACAO',
'ANO_ELEICAO',
'NUM_TURNO',
'DESCRICAO_ELEICAO',
'SIGLA_UF',
'SIGLA_UE',
'DESCRICAO_UE',
'CODIGO_CARGO',
'DESCRICAO_CARGO',
'NOME_CANDIDATO',
'SEQUENCIAL_CANDIDATO',
'NUMERO_CANDIDATO',
'CPF_CANDIDATO',
'NOME_URNA_CANDIDATO',
'COD_SITUACAO_CANDIDATURA',
'DES_SITUACAO_CANDIDATURA',
'NUMERO_PARTIDO',
'SIGLA_PARTIDO',
'NOME_PARTIDO',
'CODIGO_LEGENDA',
'SIGLA_LEGENDA',
'COMPOSICAO_LEGENDA',
'NOME_LEGENDA',
'CODIGO_OCUPACAO',
'DESCRICAO_OCUPACAO',
'DATA_NASCIMENTO',
'NUM_TITULO_ELEITORAL_CANDIDATO',
'IDADE_DATA_ELEICAO',
'CODIGO_SEXO',
'DESCRICAO_SEXO',
'COD_GRAU_INSTRUCAO',
'DESCRICAO_GRAU_INSTRUCAO',
'CODIGO_ESTADO_CIVIL',
'DESCRICAO_ESTADO_CIVIL',
'CODIGO_COR_RACA',
'DESCRICAO_COR_RACA',
'CODIGO_NACIONALIDADE',
'DESCRICAO_NACIONALIDADE',
'SIGLA_UF_NASCIMENTO',
'CODIGO_MUNICIPIO_NASCIMENTO',
'NOME_MUNICIPIO_NASCIMENTO',
'DESPESA_MAX_CAMPANHA',
'COD_SIT_TOT_TURNO',
'DESC_SIT_TOT_TURNO',
'NM_EMAIL'
]

DIRPATH = '../../dados/candidatos/'

cluster = Cluster(['10.7.40.94', '10.7.40.117'])
session = cluster.connect('eleicoes')

for filename in os.listdir(DIRPATH):
    df = pandas.read_csv(os.path.join(DIRPATH, filename), sep=';', names=header, encoding='utf-8')
    for index, row in df.iterrows():
        session.execute(
            """
            INSERT INTO candidatos2014(ID, SIGLA_UF, SEQUENCIAL_CANDIDATO, SIGLA_PARTIDO, NOME_PARTIDO, CODIGO_SEXO, DESCRICAO_SEXO, COD_GRAU_INSTRUCAO, DESCRICAO_GRAU_INSTRUCAO, CODIGO_COR_RACA, DESCRICAO_COR_RACA, DESPESA_MAX_CAMPANHA) VALUES (uuid(), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (row['SIGLA_UF'], row['SEQUENCIAL_CANDIDATO'], row['SIGLA_PARTIDO'], row['NOME_PARTIDO'], row['CODIGO_SEXO'], row['DESCRICAO_SEXO'], row['COD_GRAU_INSTRUCAO'], row['DESCRICAO_GRAU_INSTRUCAO'], row['CODIGO_COR_RACA'], row['DESCRICAO_COR_RACA'], row['DESPESA_MAX_CAMPANHA'])
        )

session.shutdown()



